[tool.poetry]
name = "deposit-service"
version = "0.1.0"
description = ""
authors = ["anzhkashina <anzhelikakashina2014yandex.ru@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
Django = "4.2.18"
psycopg2-binary = "^2.9"
dynaconf = "^3.0"
pytest = "^7.0"
ruff = "^0.0.210"
pre-commit = "^2.20"

[tool.poetry.group.dev.dependencies]
pytest-django = "^4.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
