# Generated by Django 4.2.18 on 2025-02-10 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="final_amount",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="amount",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(10000),
                    django.core.validators.MaxValueValidator(3000000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="periods",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(60),
                ]
            ),
        ),
    ]
